-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((SALES * PRICE)) as TOTAL_SALES
from BOOK B
join BOOK_SALES S on B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
where S.SALES_DATE like '2022-01%'
group by B.CATEGORY, A.AUTHOR_ID
order by AUTHOR_ID, CATEGORY DESC;